version: "3.18"

services:
  deliver:
    env_file: .env
    build:
      dockerfile: docker/vpsmanager.Dockerfile
      context: .
    image: koh/vpsmanager
    container_name: vpsmanager
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 200M
networks:
  vps-network:
    external: true
  default:
    name: kafka-network
    external: true
