package koh.service.manager.vps.kafka;

public enum KafkaReqTopic {
    TOPIC_VPS_START_REQUEST,
    TOPIC_VPS_STOP_REQUEST,
    TOPIC_VPS_CONNECT_REQUEST,
    TOPIC_VPS_CREATE_CONTAINER_REQUEST,
    TOPIC_VPS_CREATE_VOLUME_REQUEST,
    TOPIC_VPS_CREATE_NETWORK_REQUEST,
    TOPIC_VPS_CREATE_IMAGE_REQUEST
}
