package koh.service.manager.vps.kafka;

public enum KafkaRespTopic {
    TOPIC_VPS_START_RESPONSE,
    TOPIC_VPS_STOP_RESPONSE,
    TOPIC_VPS_CONNECT_RESPONSE,
    TOPIC_VPS_CREATE_CONTAINER_RESPONSE,
    TOPIC_VPS_CREATE_VOLUME_RESPONSE,
    TOPIC_VPS_CREATE_NETWORK_RESPONSE,
    TOPIC_VPS_CREATE_IMAGE_RESPONSE,
    TOPIC_VPS_CREATE_VPS_RESPONSE
}
